USE GlobalSuperstore;
GO

-- ==================================================
-- Project 23 : Error Handling
-- ==================================================

-- Objective:
-- Learn how to handle SQL Server errors using
-- TRY...CATCH, ERROR functions and best practices
-- to build reliable database applications.

GO

-- ==========================================
-- Step 1 : Introduction
-- ==========================================

-- Error Handling allows SQL Server
-- to detect runtime errors and
-- execute alternative logic instead
-- of terminating the entire process.

-- Common Error Handling Keywords:

-- TRY
-- CATCH
-- ERROR_NUMBER()
-- ERROR_MESSAGE()
-- ERROR_LINE()
-- ERROR_PROCEDURE()

GO

-- ==========================================
-- Step 2 : TRY...CATCH
-- ==========================================

-- Business Requirement:
-- Handle runtime errors gracefully
-- instead of stopping SQL execution.

BEGIN TRY

    SELECT
        100 / 10 AS Result;

END TRY

BEGIN CATCH

    PRINT 'An Error Occurred';

END CATCH;

GO


-- ==========================================
-- Step 3 : Runtime Error
-- ==========================================

-- Business Requirement:
-- Handle a runtime error using
-- TRY...CATCH.

BEGIN TRY

    SELECT
        100 / 0 AS Result;

END TRY

BEGIN CATCH

    PRINT 'Runtime Error Occurred';

END CATCH;

GO


-- ==========================================
-- Step 4 : ERROR_MESSAGE()
-- ==========================================

-- Business Requirement:
-- Display the actual error message
-- generated by SQL Server.

BEGIN TRY

    SELECT
        100 / 0 AS Result;

END TRY

BEGIN CATCH

    SELECT
        ERROR_MESSAGE() AS Error_Message;

END CATCH;

GO

-- ==========================================
-- Step 5 : ERROR_NUMBER()
-- ==========================================

-- Business Requirement:
-- Display the SQL Server error number
-- when an error occurs.

BEGIN TRY

    SELECT
        100 / 0 AS Result;

END TRY

BEGIN CATCH

    SELECT
        ERROR_NUMBER() AS Error_Number,
        ERROR_MESSAGE() AS Error_Message;

END CATCH;

GO

-- ==========================================
-- Step 6 : ERROR_LINE()
-- ==========================================

-- Business Requirement:
-- Identify the line number where
-- the error occurred.

BEGIN TRY

    SELECT
        100 / 0 AS Result;

END TRY

BEGIN CATCH

    SELECT

        ERROR_NUMBER() AS Error_Number,

        ERROR_MESSAGE() AS Error_Message,

        ERROR_LINE() AS Error_Line;

END CATCH;

GO

-- ==========================================
-- Step 7 : ERROR_PROCEDURE()
-- ==========================================

-- Business Requirement:
-- Display the Stored Procedure name
-- where the error occurred.

-- Create Sample Stored Procedure

CREATE OR ALTER PROCEDURE usp_DivideByZero
AS
BEGIN

    BEGIN TRY

        SELECT
            100 / 0 AS Result;

    END TRY

    BEGIN CATCH

        SELECT

            ERROR_NUMBER() AS Error_Number,

            ERROR_MESSAGE() AS Error_Message,

            ERROR_LINE() AS Error_Line,

            ERROR_PROCEDURE() AS Error_Procedure;

    END CATCH;

END;
GO

-- Execute Stored Procedure

EXEC usp_DivideByZero;
GO


-- ==========================================
-- Step 8 : Real-Time Business Project
-- ==========================================

-- Business Requirement:
-- Process Sales Data safely.
-- If an error occurs, display complete
-- error information.

BEGIN TRY

    SELECT

        Order_ID,
        Product_Name,
        Sales,

        Sales / 0 AS Sales_Percentage

    FROM [dbo].[Global_Superstore(CSV)];

END TRY

BEGIN CATCH

    SELECT

        ERROR_NUMBER() AS Error_Number,

        ERROR_MESSAGE() AS Error_Message,

        ERROR_LINE() AS Error_Line,

        ERROR_PROCEDURE() AS Error_Procedure,

        GETDATE() AS Error_DateTime;

END CATCH;

GO